# playbook.yml
---

- name: Deploy replicasets
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Create config directory
      file:
        path: /etc/tarantool/conf.d
        state: directory

    - name: 'Get repository setup script'
      get_url:
        url: 'https://tarantool.io/release/2/installer.sh'
        dest: '/tmp/tarantool-installer.sh'

    - name: 'Run repository setup script'
      any_errors_fatal: true
      command: bash /tmp/tarantool-installer.sh
      changed_when: false

    # - apt:
    #     upgrade: 'yes'
    #     update_cache: yes
    #     cache_valid_time: 86400
    #   ignore_errors: yes

    - name: Install dependencies
      package:
        name:
          - tarantool
        state: latest
    - name: Download the package
      shell: |
        curl https://github.com/dyne/zenswarm-storage/releases/download/v1.0.0/zenswarm-storage-1.0.0-0.deb


- name: Deploy my Tarantool Cartridge app
  become: true
  hosts: all
  become_user: root
  any_errors_fatal: true
  gather_facts: false
  roles:
    - tarantool.cartridge
  vars:
    cartridge_scenario:
      - cleanup
      - deliver_package
      - update_package
      - configure_instance
      - configure_app_config
      - restart_instance
      - wait_instance_started
      - bootstrap_vshard
