name: Zenswarm Storage CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: tarantool/setup-tarantool@v1
      with:
        tarantool-version: '2.10'
    - run: ./deps.sh
    - run: tarantoolctl rocks make
    - run: .rocks/bin/luatest -v
    - run: sudo apt-get install -y cartridge-cli
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      if: github.ref == 'refs/heads/main'
      with:
        extra_plugins: |
          @semantic-release/commit-analyzer
          @semantic-release/release-notes-generator
          @semantic-release/exec
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

