name: Zenswarm Storage CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: tarantool/setup-tarantool@v1
      with:
        tarantool-version: '2.10'
    - run: ./deps.sh
    - run: tarantoolctl rocks make
    - run: .rocks/bin/luatest -v
